BEGIN;
INSERT INTO  Pelicula (Nombre_Pelicula,Sipnosis,director,Actores,Distribuidora,Duracion,Extreno,finCartelera,IDClasificacion) VALUES("THE SUICIDE SQUAD","Los supervillanos Harley Quinn, Bloodsport, Peacemaker y muchos más que residen en la prisión Belle Reve, se unen al Task Force X para cumplir una misión imposible cuando son llevados a la remota isla de Corto Maltese.","James Gunn","Margot, Robbie, Idris Elba, John Cena, Jai Courtney ","Warner","132 min",STR_TO_DATE("01-12-2021", "%d-%m-%Y"),STR_TO_DATE("01-01-2022", "%d-%m-%Y"),4);
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_pelicula;
INSERT INTO  Poster (IDPelicula,Poster) VALUES(@mysql_id_ultima_pelicula,"/home/zchx/Documents/BDD/BDDPeliculas/THE SUICIDE SQUAD.jpg");
INSERT INTO  IdiomasPelicula (IDPelicula,IDIdioma) VALUES(@mysql_id_ultima_pelicula,1);
INSERT INTO  IdiomasPelicula (IDPelicula,IDIdioma) VALUES(@mysql_id_ultima_pelicula,2);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,4);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,6);
INSERT INTO  Sala (Nombre_Sala) VALUES("s1");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("09:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 13:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Sala (Nombre_Sala) VALUES("s2");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("17:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 21:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
COMMIT;
BEGIN;
INSERT INTO  Pelicula (Nombre_Pelicula,Sipnosis,director,Actores,Distribuidora,Duracion,Extreno,finCartelera,IDClasificacion) VALUES("Escape Room 2: Reto Mortal","Seis personas se encuentran repentinamente atrapadas en distintas habitaciones y lentamente notan qué tienen en común para sobrevivir.","Adam Robitel","Logan Miller, Taylor Russell, Indya Moore, Holland Roden","Columbia Pictures","88 min",STR_TO_DATE("25-12-21", "%d-%m-%Y"),STR_TO_DATE("25-01-22", "%d-%m-%Y"),2);
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_pelicula;
INSERT INTO  Poster (IDPelicula,Poster) VALUES(@mysql_id_ultima_pelicula,"/home/zchx/Documents/BDD/BDDPeliculas/Escape Room 2: Reto Mortal.jpg");
INSERT INTO  IdiomasPelicula (IDPelicula,IDIdioma) VALUES(@mysql_id_ultima_pelicula,1);
INSERT INTO  IdiomasPelicula (IDPelicula,IDIdioma) VALUES(@mysql_id_ultima_pelicula,3);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,7);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,3);
INSERT INTO  Sala (Nombre_Sala) VALUES("s3");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("09:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 13:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Sala (Nombre_Sala) VALUES("s1");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("17:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 21:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
COMMIT;
BEGIN;
INSERT INTO  Pelicula (Nombre_Pelicula,Sipnosis,director,Actores,Distribuidora,Duracion,Extreno,finCartelera,IDClasificacion) VALUES("Un Rescate de Huevitos","Toto y Di, amorosa pareja y padres de familia, deben lidiar con sus nuevas responsabilidades hacia sus hijos, Uly y Max cuando un malévolo coleccionista los ha secuestrado y se los ha llevado a África, donde pretende venderlos en un importante evento de alimentos gourmet.","Gabriel Riva Palacio Alatriste, Rodolfo Sealtiel Riva Palacio Alatriste","Bruno Bichir, Maité Perroni, Angélica Vale, Carlos Espejel","Huevocartoon, Huevocartoon Producciones","89 min",STR_TO_DATE("22-10-21", "%d-%m-%Y"),STR_TO_DATE("22-12-21", "%d-%m-%Y"),1);
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_pelicula;
INSERT INTO  Poster (IDPelicula,Poster) VALUES(@mysql_id_ultima_pelicula,"/home/zchx/Documents/BDD/BDDPeliculas/Un Rescate de Huevitos.jpg");
INSERT INTO  IdiomasPelicula (IDPelicula,IDIdioma) VALUES(@mysql_id_ultima_pelicula,1);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,1);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,2);
INSERT INTO  Sala (Nombre_Sala) VALUES("s4");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("08:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 11:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Sala (Nombre_Sala) VALUES("s3");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("14:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 17:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
COMMIT;
BEGIN;
INSERT INTO  Pelicula (Nombre_Pelicula,Sipnosis,director,Actores,Distribuidora,Duracion,Extreno,finCartelera,IDClasificacion) VALUES("Asalto a la Casa de Moneda","Un grupo de ladrones recluta a un ingeniero para asaltar el Banco de España el mismo día en que la selección nacional de fútbol disputa la final de la Copa del Mundo.","Jaume Balagueró","Freddie Highmore, Liam Cunningham, Astrid Bergès-Frisbey, Famke Janssen","zima entertainment","118 min",STR_TO_DATE("13-12-21", "%d-%m-%Y"),STR_TO_DATE("15-01-22", "%d-%m-%Y"),3);
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_pelicula;
INSERT INTO  Poster (IDPelicula,Poster) VALUES(@mysql_id_ultima_pelicula,"/home/zchx/Documents/BDD/BDDPeliculas/Asalto a la Casa de Moneda.jpg");
INSERT INTO  IdiomasPelicula (IDPelicula,IDIdioma) VALUES(@mysql_id_ultima_pelicula,1);
INSERT INTO  IdiomasPelicula (IDPelicula,IDIdioma) VALUES(@mysql_id_ultima_pelicula,3);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,4);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,3);
INSERT INTO  Sala (Nombre_Sala) VALUES("s2");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("10:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 13:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Sala (Nombre_Sala) VALUES("s4");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("16:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 19:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
COMMIT;
BEGIN;
INSERT INTO  Pelicula (Nombre_Pelicula,Sipnosis,director,Actores,Distribuidora,Duracion,Extreno,finCartelera,IDClasificacion) VALUES("Ainbo: La Guerrera del Amazonas","Ainbo es una joven nacida y criada en las profundidades de la selva amazónica que contará con la ayuda de sus divertidos amigos para salvar a su aldea de una catástrofe ecológica.","Jose Zelada","","Cinema Management Group","85 min",STR_TO_DATE("01-10-2021", "%d-%m-%Y"),STR_TO_DATE("01-11-2021", "%d-%m-%Y"),1);
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_pelicula;
INSERT INTO  Poster (IDPelicula,Poster) VALUES(@mysql_id_ultima_pelicula,"/home/zchx/Documents/BDD/BDDPeliculas/Ainbo: La Guerrera del Amazonas.jpg");
INSERT INTO  IdiomasPelicula (IDPelicula,IDIdioma) VALUES(@mysql_id_ultima_pelicula,1);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,6);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,2);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,5);
INSERT INTO  Sala (Nombre_Sala) VALUES("s1");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("08:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 11:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Sala (Nombre_Sala) VALUES("s2");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("14:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 17:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
COMMIT;
BEGIN;
INSERT INTO  Pelicula (Nombre_Pelicula,Sipnosis,director,Actores,Distribuidora,Duracion,Extreno,finCartelera,IDClasificacion) VALUES("Noche de Fuego","Una nina desaparece sin dejar rastro en un pueblo de la montana. Tres amigas crecen juntas, habitan las casas de los que han huido y juegan a ser mujeres cuando nadie las ve, pero los ecos oscuros de la violencia que acecha se convierten en una amenaza ineludible.","Tatiana Huezo","Olivia Lagunas, Norma Pablo, Mayra Batalla","Pimienta Films","111 min",STR_TO_DATE("10-11-2021", "%d-%m-%Y"),STR_TO_DATE("25-12-2021", "%d-%m-%Y"),2);
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_pelicula;
INSERT INTO  Poster (IDPelicula,Poster) VALUES(@mysql_id_ultima_pelicula,"/home/zchx/Documents/BDD/BDDPeliculas/Noche de Fuego.jpg");
INSERT INTO  IdiomasPelicula (IDPelicula,IDIdioma) VALUES(@mysql_id_ultima_pelicula,1);
INSERT INTO  IdiomasPelicula (IDPelicula,IDIdioma) VALUES(@mysql_id_ultima_pelicula,2);
INSERT INTO  GenerosPeliculas (IDPelicula,IDGenero) VALUES(@mysql_id_ultima_pelicula,8);
INSERT INTO  Sala (Nombre_Sala) VALUES("s5");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("09:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 13:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Sala (Nombre_Sala) VALUES("s5");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultima_sala;
INSERT INTO  Horario (Hora) VALUES("17:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
INSERT INTO  Horario (Hora) VALUES(" 21:00:00");
SELECT LAST_INSERT_ID() INTO @mysql_id_ultimo_horario;
INSERT INTO  Funcion (IDPelicula, IDSala, IDHorario) VALUES(@mysql_id_ultima_pelicula,@mysql_id_ultima_sala, @mysql_id_ultimo_horario);
COMMIT;
